stages:
  - deploy
  
build-image:
  stage: deploy
  image: "docker:19.03.12"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE/alpine-rust:$CI_COMMIT_SHORT_SHA" .
    - docker tag "$CI_REGISTRY_IMAGE/alpine-rust:$CI_COMMIT_SHORT_SHA" "$CI_REGISTRY_IMAGE/alpine-rust:latest"
    - docker push "$CI_REGISTRY_IMAGE/alpine-rust:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/alpine-rust:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always

